logging:
  level:
    root: INFO

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    hikari:
      poolName: Hikari
      auto-commit: false

  h2:
    console:
      enabled: true

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
